"""Agent state and planning domain models."""

from __future__ import annotations

from typing import Any, Dict, List, Optional
from uuid import UUID
from pydantic import BaseModel, Field, ConfigDict
from medistock_agents.models.tool_models import (
    CandidateFacility,
    DistanceCalculationResult,
    FacilityLocation,
    QuantityCalculationResult,
    ToolExecutionRecord,
)


class RedistributionProposal(BaseModel):
    """Structured proposal generated by the Redistribution Agent."""
    model_config = ConfigDict(populate_by_name=True)

    selected_facility_id: Optional[UUID] = Field(None, alias="selectedFacilityId")
    selected_facility_name: Optional[str] = Field(None, alias="selectedFacilityName")
    proposed_quantity: int = Field(0, alias="proposedQuantity")
    distance_km: float = Field(0.0, alias="distanceKm")
    duration_minutes: float = Field(0.0, alias="durationMinutes")
    provider: str = "LangGraphRedistributionAgent"
    reasoning: str = ""
    prompt_tokens: int = Field(320, alias="promptTokens")
    completion_tokens: int = Field(120, alias="completionTokens")


class RedistributionAgentState(BaseModel):
    """LangGraph execution state for redistribution planning."""
    model_config = ConfigDict(arbitrary_types_allowed=True)

    workflow_run_id: UUID
    destination_facility_id: UUID
    medicine_id: UUID
    shortage_quantity: int
    additional_context: Optional[str] = None

    # Intermediate state populated by graph nodes
    destination_location: Optional[FacilityLocation] = None
    candidate_facilities: List[CandidateFacility] = Field(default_factory=list)
    selected_candidate: Optional[CandidateFacility] = None
    distance_result: Optional[DistanceCalculationResult] = None
    quantity_result: Optional[QuantityCalculationResult] = None
    proposal: Optional[RedistributionProposal] = None
    tool_calls: List[ToolExecutionRecord] = Field(default_factory=list)

    success: bool = True
    error_message: Optional[str] = None
